import { promises as fs } from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

/**
 * OrchestraController
 * 
 * Acts as the bridge between the User interface (Chat/CLI) and the BMAD Orchestra MCP server.
 * Handles task dispatching, context injection (via file paths), and result logging to artifacts.
 */
export class OrchestraController {
  private workspaceRoot: string;
  private artifactPath: string;

  constructor(workspaceRoot: string) {
    this.workspaceRoot = workspaceRoot;
    // Defaults to writing work_log.md in the current directory for visibility
    this.artifactPath = path.join(workspaceRoot, 'work_log.md');
  }

  /**
   * Checks if the environment is ready for Cloud Agent handover.
   * Verifies Git and GitHub connectivity.
   */
  async ensureCloudReadiness(): Promise<boolean> {
    console.log(`[Orchestra] ☁️  Checking Cloud Readiness...`);
    let ready = true;
    let report = "";

    // 1. Check Git
    try {
      await fs.stat(path.join(this.workspaceRoot, '.git'));
      report += "- ✅ Git Repository: Detected\n";
    } catch {
      report += "- ❌ Git Repository: Not found (Run `git init`)\n";
      ready = false;
    }

    // 2. Check GitHub CLI (gh)
    try {
      const { stdout, stderr } = await execAsync('gh auth status');
      if (stdout.includes('Logged in') || stderr.includes('Logged in')) {
        report += "- ✅ GitHub Auth: Authenticated via `gh`\n";
      } else {
        throw new Error("Not logged in");
      }
    } catch (e) {
      report += "- ⚠️ GitHub Auth: Not detected (Run `gh auth login`)\n";
      // We don't block on this, strictly speaking, but it's recommended
    }

    // 3. Cursor Login Reminder
    report += "- ℹ️  Cursor Cloud: Please ensure you are logged in via Cursor Settings > General > Account\n";

    await this.logToArtifact('☁️ Cloud Readiness Report', report);
    console.log(report);

    return ready;
  }

  /**
   * Dispatches a "Spec Generation" task to the BMAD Orchestra system.
   * The goal is to produce a detailed 'Handover Specification' for a Cloud Agent.
   * 
   * @param topic The feature or task to plan.
   * @param contextFiles Optional list of file paths to include as context.
   */
  async dispatchSpecGeneration(topic: string, contextFiles: string[] = []): Promise<void> {

    // Check readiness first
    await this.ensureCloudReadiness();

    console.log(`[Orchestra] Generating Spec for: "${topic}"`);

    // 1. Prepare Context & Spec Prompt
    const contextInfo = contextFiles.length > 0
      ? `\n\nContext Files:\n${contextFiles.map(f => `- ${f}`).join('\n')}`
      : '';

    const prompt = `
    You are the Architect. Plan the implementation for: "${topic}".
    ${contextInfo}
    
    Output a valid Markdown Implementation Specification (Spec-Doc) that a Junior Developer (Cloud Agent) can follow blindly.
    Include:
    - Goal
    - File Changes (New/Modify) - Be specific with paths.
    - Code Snippets / Pseudo-code
    - Verification Steps
    `;

    // 2. Log key events
    await this.logToArtifact('📐 Spec Generation Initiated', `**Topic**: ${topic}\n\n**Brief**: To generate a handover spec for Cloud Agents.`);

    // 3. Simulate Task Dispatch (In real flow, this calls MCP)
    // For demonstration, we will write a placeholder "Spec" file to simulate the result.
    await this.simulateSpecCreation(topic, prompt);
  }

  /**
   * Helper to simulate the agent writing a Spec file.
   * In production, the Agent (Sisyphus) would use the 'write_file' tool directly.
   */
  private async simulateSpecCreation(topic: string, fullPrompt: string) {
    const safeTopic = topic.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const specDir = path.join(this.workspaceRoot, 'specs');
    const specFile = path.join(specDir, `${safeTopic}_spec.md`);

    await fs.mkdir(specDir, { recursive: true });

    const mockSpecContent = `# Spec: ${topic}

> **Generated by BMAD Orchestra**
> **For Cloud Agent Execution**

## 1. Objective
Implement the requested feature "${topic}" based on the provided context.

## 2. Implementation Details
(This section would be populated by Atlas/Hermes with specific architectural instructions)

## 3. Handover Checklist
- [ ] Connect this repo to Cursor Cloud.
- [ ] Feed this Spec file to the Agent.
- [ ] Review PR.
`;

    await fs.writeFile(specFile, mockSpecContent);
    await this.logToArtifact('✅ Spec Generated', `Spec file created at: \`${specFile}\`\n\nReady for Cloud Agent handover.`);
    console.log(`[Orchestra] Spec created: ${specFile}`);
  }

  /**
   * Appends specific events or logs to the project's work log artifact.
   */
  public async logToArtifact(header: string, content: string) {
    const timestamp = new Date().toLocaleTimeString();
    const entry = `\n## [${timestamp}] ${header}\n\n${content}\n---\n`;

    try {
      await fs.appendFile(this.artifactPath, entry);
      console.log(`[Orchestra] Artifact updated: ${this.artifactPath}`);
    } catch (error) {
      console.error(`[Orchestra] Failed to write to artifact:`, error);
    }
  }
}

// CLI Entry Point
if (require.main === module) {
  const rootDir = process.cwd();
  const controller = new OrchestraController(rootDir);

  const args = process.argv.slice(2);
  const topic = args[0] || "Refactor Authentication Logic";
  const files = args.slice(1);

  controller.dispatchSpecGeneration(topic, files).catch(err => console.error("Dispatch Error:", err));
}
